CREATE OR REPLACE TABLE registrations (
	ID INT NOT NULL AUTO_INCREMENT,
	email VARCHAR(100) NOT NULL,
	phone VARCHAR(20) NOT NULL,
	remarks VARCHAR(1000),
	INDEX `IDX_ID` (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE OR REPLACE table persons (
	ID INT NOT NULL AUTO_INCREMENT, 
	REGISTRATION_ID INT NOT NULL, 
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	INDEX `IDX_ID` (`ID`), 
	CONSTRAINT FOREIGN KEY (REGISTRATION_ID) REFERENCES REGISTRATIONS (ID)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;

CREATE OR REPLACE TABLE deregistrations (
	ID INT NOT NULL AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	INDEX `IDX_ID` (`ID`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
